FROM dunglas/frankenphp
 
RUN install-php-extensions pcntl
	pdo_pgsql \
	gd \
	intl \
	zip \
	opcache \
	cli \
	common \
	mbstring \
	curl \
	xml \
	bcmat

COPY . /app
 
ENTRYPOINT ["php", "artisan", "octane:frankenphp"]