services:
  web:
    build:
      context: .
      dockerfile: infrastructure/web/Dockerfile
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "8080:8000"
    volumes:
      - .:/app