[supervisord]
nodaemon=true

[program:octane]
command=php /app/artisan octane:frankenphp
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/storage/logs/octane.log

[program:queue]
command=php /app/artisan queue:work
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/storage/logs/queue.log