version: 2.1
jobs:
  build-development:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t triastartya/api-retail:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            docker push triastartya/api-retail:$CIRCLE_SHA1
            docker tag triastartya/api-retail:$CIRCLE_SHA1 triastartya/api-retail:dev-latest
            docker push triastartya/api-retail:dev-latest
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:hQ5CqSmDxYcA4Lnw5PxRF1d+IMIvioaMeObtbnzFaaw'
      - run:
          name: Deploy app to server demo
          command: |
            ssh -o StrictHostKeyChecking=no trias@203.194.112.71 "cd /home/his-admin/pis-api/ && ./deploy.sh"
workflows :
  basic-workflow:
    jobs:
      - build-development:
          filters:
            branches:
              only:
                - main