version: 2.1
jobs:
  build-development:
    machine:
      image: ubuntu-2204:2024.01.2
    # If running ARM, the resource class needs to be added. Omitting this defaults to amd64
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: install php8.1
          command: sudo apt install --no-install-recommends php8.1
      - run:
          name: install php-extention
          command: sudo apt-get install -y php8.1-cli php8.1-common php8.1-mysql php8.1-zip php8.1-gd php8.1-mbstring php8.1-curl php8.1-xml php8.1-bcmath
      - run:
          name: install composer
          command: |
            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
            HASH=`curl -sS https://composer.github.io/installer.sig`
            echo $HASH
            php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
            composer
      - run:
          name: install install
          command: |
            composer install
            php artisan octane:install --server=frankenphp
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t triastartya/api-retail:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            docker push triastartya/api-retail:$CIRCLE_SHA1
            docker tag triastartya/api-retail:$CIRCLE_SHA1 triastartya/api-retail:latest
            docker push triastartya/api-retail:latest
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:hQ5CqSmDxYcA4Lnw5PxRF1d+IMIvioaMeObtbnzFaaw'
      - run:
          name: Deploy app to server
          command: |
            ssh -o StrictHostKeyChecking=no trias@203.194.112.71 "cd aplikasi && ./deployer-api-retail.sh"
workflows :
  basic-workflow:
    jobs:
      - build-development:
          filters:
            branches:
              only:
                - main