version: 2.1
jobs:
  build-development:
    docker:
      - image: cimg/base:2022.05
    steps:
      - add_ssh_keys:
          fingerprints:
            - '6f:b2:e2:7c:b0:25:2d:98:7a:30:e2:8e:21:7b:b6:f2'
      - run:
          name: Deploy app to server development
          command: |
            ssh -o StrictHostKeyChecking=no root@203.175.10.195 "cd /var/www/html/trijuna_retail_backend && ./deploy.sh"
workflows :
  basic-workflow:
    jobs:
      - build-development:
          filters:
            branches:
              only:
                - main
