FROM dunglas/frankenphp

RUN apt update -y
RUN apt install curl -y

RUN install-php-extensions \
	pdo_mysql \
	gd \
	intl \
	zip \
	opcache
 
COPY . /app
 
ENTRYPOINT ["php", "artisan", "octane:frankenphp"]